method: L1
arch: resnet56
dataset: cifar10
batch_size: 256
batch_size_prune: 256
wd: 0.0005
base_model_path: Experiments/teacher-resnet56-cifar10-wd0.0005-imagenetmean_SERVER138-20200528-084225/weights/checkpoint_best.pth

# lr schedule
lr_pick: 0.001
lr_prune: 0.001
# lr_ft: {"0":0.01, "60":0.001, "90":0.0001}
# epoch: 120
lr_ft: {"0":0.01, "120":0.001, "180": 0.0001} # 2xtime
epochs: 240

# prune ratio
# stage_pr: '[0, 0.5, 0.5, 0.5, 0]' # last 0 is for FC layer
# stage_pr: '[0, 0.7, 0.7, 0.7, 0]'
# stage_pr: '[0, 0.9, 0.9, 0.9, 0]'
# stage_pr: '[0, 0.925, 0.925, 0.925, 0]'
# stage_pr: '[0, 0.95, 0.95, 0.95, 0]'
# stage_pr: '[0, 0.75, 0.75, 0.32, 0]' # 2.55x
stage_pr: '[0, 0.85, 0.65, 0.29, 0]' # 2.56x
skip_layers: '[]'

# prune reg related
update_reg_interval: 10 # 5
stabilize_reg_interval: 5000
reg_granularity_prune: 0.0001
reg_granularity_pick: 0.00001
reg_granularity_recover: -0.0001
reg_upper_limit: 1
reg_upper_limit_pick: 0.01

AdaReg_only_picking: false
AdaReg_revive_kept: false
pick_pruned_interval: 1
