


method: IncReg
dataset: imagenet
batch_size: 256
batch_size_prune: 64

# lr schedule
lr_prune: 0.001
lr_ft: {"0":0.01,"15":0.001,"45":0.0001,"60":0.00001}
epochs: 75

# prune ratio
# stage_pr: '[0, 0.3, 0.3, 0.3, 0.14]' # res50, 1.49x
# stage_pr: '[0, 0.6, 0.6, 0.6, 0.21]' # res50, 2.31x
# stage_pr: '[0, 0.68, 0.68, 0.68, 0.5]' # res50, 3.06x
# stage_pr: '[0, 0.827, 0.827, 0.827, 0.827, 0.827]' # res50, compression ratio = 0.827
stage_pr: '[0, 0.95, 0.95, 0.95, 0.95, 0.95]' # res50, compression ratio = 0.95
skip_layers: '[]'

# prune reg related
update_reg_interval: 5
stabilize_reg_interval: 40000
reg_granularity_prune: 0.0001
reg_upper_limit: 1
