method: L1
dataset: imagenet
batch_size: 256
batch_size_prune: 64 # dummy argument, not really used 

# lr schedule
lr_prune: 0.001
lr_ft: {"0":0.1,"30":0.01,"60":0.001,"90":0.0001,"105":0.00001}
epochs: 120

# prune ratio
stage_pr: '[0,0,0,0,0,0]' # train from scratch
skip_layers: '[]'